### ISSUE TITLE
consider making default and recommended token Branca instead of JWT

### ISSUE THREAD

**Issue by jmellicker** [SocketCluster/asyngular#8]
I think it might be good to consider switching to [https://branca.io/](https://branca.io/) for the default and recommended token for Asyngular. JWT has a security problem that has given it a bad name on the interwebs, while Branca forces XChaCha20-Poly1305 (so no security "loophole").

Also, Branca has the advantage of being encrypted, in some cases you need this (you can encrypt JWT of course but it's an extra step).

**Comment by jondubois** [comment]
I'm still keeping an eye on this project. I think it may be worthwhile to implement as an optional AuthEngine. Would be perfect for a lot of use cases. That said, there are a lot of other factors to consider when switching defaults:

- Some users may not want to encrypt their tokens because they want to read them on the front end (some users only want the temper-proof aspect of JWT).
- Encrypting instead of just signing may have different performance characteristics.
- A lot of users of SC/Asyngular share the same JWTs between multiple systems/microservices so JWT has some kind of network effect already.
